services:
  - type: web
    name: sentinela-virgidrex
    runtime: python
    buildCommand: "python3.11 -m pip install --break-system-packages -r requirements.txt"
    startCommand: "python3.11 main.py"
    envVars:
      - key: PYTHONPATH
        value: /opt/render/.local/lib/python3.11/site-packages
