services:
  - type: web
    name: sentinela-virgidrex
    runtime: python
    branch: main
    buildCommand: pip install --break-system-packages -r requirements.txt
    startCommand: python3.11 main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: ${TELEGRAM_BOT_TOKEN}
      - key: BSCSCAN_API_KEY
        value: ${BSCSCAN_API_KEY}
      - key: TOKEN_ADDRESS
        value: ${TOKEN_ADDRESS}
      - key: MAX_TOKENS
        value: ${MAX_TOKENS}
      - key: GRUPO_HOLDERS
        value: ${GRUPO_HOLDERS}
      - key: GRUPO_ESPERA
        value: ${GRUPO_ESPERA}
