services:
  - type: web
    name: sentinela-virgidrex
    runtime: python
    branch: main
    buildCommand: "pip install --user -r requirements.txt"
    startCommand: "env PYTHONPATH=$HOME/.local/lib/python3.11/site-packages python3.11 main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromDotEnv: true
      - key: BSCSCAN_API_KEY
        fromDotEnv: true
      - key: TOKEN_ADDRESS
        fromDotEnv: true
      - key: MAX_TOKENS
        fromDotEnv: true
      - key: GRUPO_HOLDERS
        fromDotEnv: true
      - key: GRUPO_ESPERA
        fromDotEnv: true
