services:
  - type: web
    name: sentinela-virgidrex
    runtime: python
    pythonVersion: 3.11.9
    branch: main
    buildCommand: "pip install --target=. -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: ${TELEGRAM_BOT_TOKEN}
      - key: BSCSCAN_API_KEY
        value: ${BSCSCAN_API_KEY}
      - key: TOKEN_ADDRESS
        value: ${TOKEN_ADDRESS}
      - key: MAX_TOKENS
        value: ${MAX_TOKENS}
      - key: GRUPO_HOLDERS
        value: ${GRUPO_HOLDERS}
      - key: GRUPO_ESPERA
        value: ${GRUPO_ESPERA}
